version: '3'

services:
#Servers
  ms-sql-server-orders:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd!!!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  ms-sql-server-products:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
  
  #API's
  manage-orders-api:
    build: ../../../customerorderapi/
    environment:
      DBServer: "ms-sql-server-orders"
    ports:
      - "8081:80"
  manage-products-api:
    build: ../../../manageProductsAPI/
    environment:
      DBServer: "ms-sql-server-products"
    ports:
      - "8080:80"
  
  #Web APPS
  staff-app:
    build: .
    environment: 
      - ManageOrdersUrl=http://manage-orders-api
      - ManageProductsUrl=http://manage-products-api
    ports:
      - 5100:80
#  ms-sql-server-staff:
#    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
#    environment:
#      ACCEPT_EULA: "Y"
#      SA_PASSWORD: "Pa55w0rd!!!"
#      MSSQL_PID: Express
#    ports:
#      - "1434:1433"
#  manage-staff-api:
#    image: staffaccountserviceapi
#    environment:
#      DBServer: "ms-sql-server-staff"
#    ports:
#      - "8081:80"
