version: '3'

services:
  ms-sql-server-customers:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd!!!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  manage-customers-api:
    build: ../../../customerorderapi/
    environment:
      DBServer: "ms-sql-server-customers"
    ports:
      - "8081:80"
  staff-app:
    build: .
    environment: 
      - ManageCustomersUrl=http://manage-customers-api
    ports:
      - 5100:80
#  ms-sql-server-staff:
#    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
#    environment:
#      ACCEPT_EULA: "Y"
#      SA_PASSWORD: "Pa55w0rd!!!"
#      MSSQL_PID: Express
#    ports:
#      - "1434:1433"
#  manage-staff-api:
#    image: staffaccountserviceapi
#    environment:
#      DBServer: "ms-sql-server-staff"
#    ports:
#      - "8081:80"
